version: "3.9"
services:
  app:
    depends_on:
      - db
    build: .
    stdin_open: true
    tty: true
    ports:
      - "4001-4002:4001-4002"
      - "4000:4000"
    volumes:
      - .:/usr/src/game
  db:
    image: postgres:13-alpine
    env_file:
      - .env.local
    environment:
      POSTGRES_DB: evennia_development
